#!/usr/bin/env python
"""
    This file is part of SleekBot. http://github.com/hgrecco/SleekBot
    See the README file for more information.


SleekBot is a pluggable Jabber/XMPP bot based on SleekXMPP.
"""

__author__ = 'Hernan E. Grecco <hernan.grecco@gmail.com>'
__license__ = 'MIT License/X11 license'

import os
import logging
import sys
import time

from optparse import OptionParser

from sleekbot.sleekbot import SleekBot, END_STATUS
from sleekbot.configure import Configure

# Default home dir and config file
WORK_DIR = os.path.join(os.environ["HOME"], '.sleekbot')
CONFIG_FILE = 'config.xml'

if __name__ == '__main__':
    OPTP = OptionParser(usage="usage: %prog [options] [configuration_file]")
    OPTP.add_option('-n', '--new', help='Create a new configuration file',
                    action='store_const', dest='new',
                    const=True, default=False)
    OPTP.add_option('-c', '--configure', help='Modify configuration file',
                    action='store_const', dest='config',
                    const=True, default=False)
    OPTP.add_option('-q', '--quiet', help='set logging to ERROR',
                    action='store_const', dest='loglevel',
                    const=logging.ERROR, default=logging.INFO)
    OPTP.add_option('-d', '--debug', help='set logging to DEBUG',
                    action='store_const', dest='loglevel',
                    const=logging.DEBUG, default=logging.INFO)
    OPTP.add_option('-v', '--verbose', help='set logging to COMM',
                    action='store_const', dest='loglevel', const=5,
                    default=logging.INFO)
    OPTS, ARGS = OPTP.parse_args()
    
    if len(ARGS) > 0:
        CONFIG_FILE = ARGS[0]
    if OPTS.new:
        config = Configure(CONFIG_FILE, WORK_DIR)
        config.create()
        exit()
    if OPTS.config:
        config = Configure(CONFIG_FILE, WORK_DIR)
        config.config()
        exit()

    logging.basicConfig(level=OPTS.loglevel,
                        format='%(levelname)-8s %(message)s')
       
    if not os.path.exists(CONFIG_FILE):
        os.chdir(WORK_DIR)
        if not os.path.exists(CONFIG_FILE):
            print("\n\tNo configuration file found. Please create one.\n")
            OPTP.print_help()
            sys.exit()
    
    WORK_DIR = os.path.dirname(os.path.abspath(CONFIG_FILE))
    sys.path.append(WORK_DIR)
    
    SHOULD_RESTART = True
    while SHOULD_RESTART:
        SHOULD_RESTART = False
        logging.info('Work directory is: %s', WORK_DIR)
        logging.info('Loading config file: %s', CONFIG_FILE)

        BOT = SleekBot(CONFIG_FILE)
        BOT.start()
        BOT.process(threaded=False)
        while not BOT.state['disconnecting']:
            time.sleep(1)
        #this does not work properly. Some thread is runnng
        SHOULD_RESTART = (BOT.end_status == END_STATUS.restart)

    logging.info("SleekBot finished")
